### ISSUE TITLE
Metadata header highlighting bug

### ISSUE THREAD

**Issue by fonnesbeck** [fletcher/markdown.tmbundle#2]
One small bug in the syntax highlighting relates to headers with words separated by spaces: these do not get properly highlighted by the bundle. A small tweak to the begin and end entries in meta.header.multimarkdown seems to fix this:

begin = '^([A-Za-z0-9][A-Za-z0-9 ]_):\s_';
end = '^$|^(?=[ A-Za-z0-9]+:)';

Just an addition of two whitespace characters.

**Comment by fletcher** [comment]
Could you provide an example showing the problem?

**Comment by fonnesbeck** [comment]
I'm "between Macs" at the moment, and so do not have access to TextMate right now, but will post a screen shot as soon as I do. Basically, any header keyword that consisted of more than one word separated by a space did not get coloured as a header.

**Comment by fletcher** [comment]
I'm not seeing this behavior, at least as I understand it.

So, you're saying that something like the following doesn't work properly?

# This is a multiword header

F-

**Comment by fletcher** [comment]
oops - that got interpreted...

```
# This is a multiword header #
```

**Comment by fonnesbeck** [comment]
Sorry, maybe I'm not using the appropriate term. I'm talking about the metadata key values. So, for example, "Title:" is colorized properly, whereas "Base Header Level:" is not.

**Comment by fletcher** [comment]
I still have been unable to recreate this.  Please send example and screenshot, and we can reopen.

**Comment by urschrei** [comment]
I see it too (I think). Do you mean this?
http://dl.dropbox.com/u/21382/photos/TextMate.png

**Comment by fletcher** [comment]
Can you send me a textmate theme, so I can try and replicate?  When I mess around with it, I don't have any trouble...

**Comment by urschrei** [comment]
Here's the one I'm using in the screenshot: http://www.infinitered.com/settings/IR_Black.tmTheme.zip
The problem doesn't exist when using the MultiMarkdown theme (but seems to reappear in others)

**Comment by fletcher** [comment]
It's a problem with the other themes - they are pulling colors from other elements, rather than the MMD elements.

The one I include works.  There may be some conflicts with the other elements you have defined in your version.  If you track it down, let me know and I can try and make changes if appropriate.
