### ISSUE TITLE
TextMate variables not being utilized

### ISSUE THREAD

**Issue by fonnesbeck** [fletcher/markdown.tmbundle#3]
I am using a selection of shell variables that I have defined in TextMate. For example,

Author:             ${TM_FULLNAME}  
Affiliation:        ${TM_ORGANIZATION_NAME}  

However, when I process the mmd file using the bundle, these variables are not utilized, but instead are being treated as literal values. So, in place of my name, the generated pdf displays ${TM_FULLNAME}. I have downloaded and installed the most recent version of the bundle.

**Comment by fletcher** [comment]
These variables are used by TextMate, not by MultiMarkdown.  They are only processed when used in snippets or in templates.

Unless I am misunderstanding you, this is not an issue with MultiMarkdown, but rather an issue with the way you are using TextMate.
