### ISSUE TITLE
Table cleanup can't handle more than one table in a row?

### ISSUE THREAD

**Issue by joeyj** [fletcher/markdown.tmbundle#4]
The below syntax cannot be cleaned up (notice the two line breaks between the tables). If text or any other non-table element is placed between the tables, the cleanup command works. I would expect that a single line-break would treat them as the same table and more than 1 line-break to treat them as separate tables.

<pre>
|h1|h2|
|-|-|
|c1|c2|

|h3|h4|
|-|-|
|c3|c4|
</pre>

**Comment by fletcher** [comment]
I don't think there are any other structures in Markdown that treat a single line break as different from 2 or more line breaks, so I would prefer for this behavior to be consistent.
