### ISSUE TITLE
bundle item popup

### ISSUE THREAD

**Issue by ansdma** [fletcher/markdown.tmbundle#7]
Hi,
after replacing markdown bundle with your when I click on the gear icon I get an alert saying `bundle item popup` 
![bundle item popup](https://www.evernote.com/shard/s19/sh/f45ca7b6-6a74-4267-b8d0-28c61faf3cb1/edb1090c200a7b9fc384ce993c7ce76a/res/b979f94c-8b43-43e2-bf26-455ae176a55c/TextMate-20120810-063821.jpg.jpg)

**Comment by fletcher** [comment]
That's a TM 2 issue apparently.  I can't help with it, but others have reported similar problems on the TM discussion list in the past.  Perhaps they can help sort out the problem?

FTP

On Aug 10, 2012, at 1:41 AM, Ans Alghamdi wrote:

> Hi,
> after replacing markdown bundle with your when I click on the gear icon I get an alert saying bundle item popup 
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Fletcher T. Penney
fletcher@fletcherpenney.net

**Comment by fletcher** [comment]
That's apparently a TM 2 issue, not an issue with my bundle.

**Comment by ansdma** [comment]
Thanks for the prompt reply. I went to close the issue but seems you
already closed and deleted it. Thanks anyway.

Best
Ans

**Comment by fletcher** [comment]
If you (or someone else) does discover a fix I need to implement in order to work with TM 2, let me know and I'll do what I can.  I have not upgraded, since TM 1 still does everything I need and I am busy enough with bug fixes/upgrades in my own software at the moment.  :)
