### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tangledhelix** [fletcher/markdown.tmbundle#9]
Under what license is this released? I have been looking to try to make a Multimarkdown bundle for the Atom editor, using this as a starting point, but it's not clear how you have licensed this stuff...

**Comment by fletcher** [comment]
This is a fork of the original markdown bundle in the textmate repo (see link at top of the page).

The license from that project is spelled out on the main page:

https://github.com/textmate/markdown.tmbundle

This project shares that license (for code written by me).  MultiMarkdown itself is a separate project and licensed in that project.  But I believe I took all of the MMD code out of this project.

Probably for anything useful to come out of this, you would have to go back to the original bundle.  Mine was just a few tweaks on top of that project, and I haven't looked at it in years.
